### ISSUE TITLE
-

### ISSUE THREAD

**Issue by momaqbol** [tm2josep/2d-platformer#1]

**Comment by tm2josep** [comment]
You have to run the dev server.

console:

$ npm install
$ npm start

new console: (leave the old one open)

$ npm serve

Also, this is a very poorly made personal project, so I wouldn't use this as a reference to learn.

**Comment by Enjoy2Live** [comment]
is this how the actual game would look like?
![image](https://user-images.githubusercontent.com/27841994/71195407-ec213d80-229e-11ea-9c5e-96aba43263ce.png)

**Comment by tm2josep** [comment]
Yes, Like I said, It's currently incomplete. I only made this for my own learning. If you wish to continue developing that is your decision.

It has tile collision, sprite animation and basic camera movement. That's it.

**Comment by Enjoy2Live** [comment]
I might, who really knows anyway thanks for helping me out running it.
